AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS App Runner service for Todo App'

Parameters:
  ServiceName:
    Type: String
    Default: todo-app-service
    Description: Name of the App Runner service
  ECRRepositoryURI:
    Type: String
    Description: ECR Repository URI
  ImageTag:
    Type: String
    Default: latest
    Description: Docker image tag
  AWSRegion:
    Type: String
    Default: us-east-1
    Description: AWS Region
  DefaultUserId:
    Type: String
    Default: default-user
    Description: Default user ID for the application

Resources:
  # App Runner Instance Role
  AppRunnerInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: tasks.apprunner.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess
      Policies:
        - PolicyName: CloudWatchLogsPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - logs:DescribeLogStreams
                Resource: "*"

  # App Runner Access Role
  AppRunnerAccessRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: build.apprunner.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSAppRunnerServicePolicyForECRAccess

  # App Runner Service
  AppRunnerService:
    Type: AWS::AppRunner::Service
    Properties:
      ServiceName: !Ref ServiceName
      SourceConfiguration:
        ImageRepository:
          ImageIdentifier: !Sub "${ECRRepositoryURI}:${ImageTag}"
          ImageConfiguration:
            Port: '3000'
            RuntimeEnvironmentVariables:
              - Name: NODE_ENV
                Value: production
              - Name: AWS_REGION
                Value: !Ref AWSRegion
              - Name: DEFAULT_USER_ID
                Value: !Ref DefaultUserId
          ImageRepositoryType: ECR
        AutoDeploymentsEnabled: true
      InstanceConfiguration:
        Cpu: 1 vCPU
        Memory: 2 GB
        InstanceRoleArn: !GetAtt AppRunnerInstanceRole.Arn
      HealthCheckConfiguration:
        Protocol: HTTP
        Path: /
        IntervalSeconds: 10
        TimeoutSeconds: 5
        HealthyThresholdCount: 1
        UnhealthyThresholdCount: 5

Outputs:
  AppRunnerServiceUrl:
    Description: App Runner service URL
    Value: !Sub "https://${AppRunnerService.ServiceUrl}"
    Export:
      Name: !Sub "${AWS::StackName}-ServiceUrl"
  
  AppRunnerServiceArn:
    Description: App Runner service ARN
    Value: !GetAtt AppRunnerService.ServiceArn
    Export:
      Name: !Sub "${AWS::StackName}-ServiceArn"