AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS App Runner service for Todo App from GitHub source'

Resources:
  # App Runner Instance Role for your application code to access DynamoDB
  AppRunnerInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: tasks.apprunner.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess

  # App Runner Connection to GitHub
  AppRunnerGitHubConnection:
    Type: AWS::AppRunner::Connection
    Properties:
      ConnectionName: todo-app-connection
      ProviderType: GITHUB

  # App Runner Service
  AppRunnerService:
    Type: AWS::AppRunner::Service
    Properties:
      ServiceName: todo-app-service
      InstanceConfiguration:
        Cpu: 1 vCPU
        Memory: 2 GB
        InstanceRoleArn: !GetAtt AppRunnerInstanceRole.Arn
      SourceConfiguration:
        AutoDeploymentsEnabled: true
        AuthenticationConfiguration:
          # Use the ARN from the Connection resource created above
          ConnectionArn: !GetAtt AppRunnerGitHubConnection.ConnectionArn
        CodeRepository:
          # Tell App Runner to look for 'apprunner.yaml' in your repo
          CodeConfiguration:
            ConfigurationSource: REPOSITORY
          RepositoryUrl: https://github.com/realwarrenlee/todo-app
          SourceCodeVersion:
            Type: BRANCH
            Value: main
      HealthCheckConfiguration:
        Protocol: TCP # Use TCP for port-only checks, which is more reliable at startup
        Port: '3000'

Outputs:
  AppRunnerServiceUrl:
    Description: App Runner service URL
    Value: !GetAtt AppRunnerService.ServiceUrl
